camel:
    springboot:
        main-run-controller: true
        xml-routes: classpath:camel/*.xml

spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: false
                connection:
                    charSet: UTF-8
                    useUnicode: true
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                temp:
                    use_jdbc_metadata_defaults: false
