camel:
    springboot:
        main-run-controller: true
        xml-routes: classpath:camel/StudyPullJob.xml

spring:
    jmx.unique-names: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: false
                connection:
                    charSet: UTF-8
                    useUnicode: true
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                temp:
                    use_jdbc_metadata_defaults: false

management:
    server.port: 9090
    security.enabled: false
    endpoints.jmx.domain: rcc-dosewatch
