spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                connection:
                    charSet: UTF-8
                    useUnicode: true
                temp:
                    use_jdbc_metadata_defaults: false
